### ISSUE TITLE
Sorting with concat 2.1.0

### ISSUE THREAD

**Issue by jhodrien** [jkroepke/puppet-module-autofs#6]
Works just fine with older concat (1.2.5) but with the newer concat, there's no sorting of the automount map files.

Not sure what the best fix is for this.  An addition of order => numeric to the concat definition resolves it for me, but I'm not sure that's the best solution.

Thoughts?

**Comment by jkroepke** [comment]
Hi.

did you mean there is a order by random, changing sometimes the file without new mounts?

**Comment by jhodrien** [comment]
No, it's not that bad, but it's definitely a regression compared to running with 1.2.5.  With 1.2.5, you'd get your mounts sorted alphabetically.  With 2.1.0 I've observed it to be a stable order, but then I'm not sure that's a guarantee.  It doesn't obviously map to the order they were declared in, or anything else I can decipher.  Fixing to numeric order would change the behaviour of this module running with 1.2.5 (where the default sort is alpha).

I raised an upstream ticket with concat, as the bug's fundamentally theirs:

https://tickets.puppetlabs.com/browse/MODULES-3488

Possibly one to just sit on until they've weighed in, but I thought it was worth raising.

Thanks.

**Comment by jkroepke** [comment]
HI @jhodrien 

does concat 2.2 resolve this problem?

**Comment by jhodrien** [comment]
Yes, sorry for not updating this.  Fixed Monday solves this.

jh

**Comment by jkroepke** [comment]
Fine, thanks.
