### ISSUE TITLE
Add a realease tag for 2.0.3

### ISSUE THREAD

**Issue by jschaeff** [jkroepke/puppet-module-autofs#7]
Hi there,

I'm very interested in the new "maptype" feature of your module. Could you add a git tag for the 2.0.3 release so that it can be referenced in puppet forge and in a Puppetfile ?

Thanks

**Comment by jkroepke** [comment]
Hi @jschaeff 

before I release the 2.0.3, I want to fix my travis test. https://travis-ci.org/jkroepke/puppet-module-autofs

I tried so much variants from other repos .... none of them will work I like.

**Comment by jkroepke** [comment]
Done.

https://forge.puppet.com/jkroepke/autofs

**Comment by jschaeff** [comment]
Excellent, thanks !
