### ISSUE TITLE
options default value in autofs::mount breaks autofs

### ISSUE THREAD

**Issue by atduke** [jkroepke/puppet-module-autofs#8]
Hi,

I updated your autofs module to the latest version today and after a few minutes autofs on all my servers failed to mount shares ;-)

In autofs::mount, you changed the default options from undef to "rw". This string breaks autofs, because options in map files are expected to start with a dash. You probably should set the default options to "-rw".

Cheers,
Tom.

**Comment by jkroepke** [comment]
Thanks for the info.
